---

- name: Determine OS if facts not already gathered
  setup:
    gather_subset:
      - '!all'
  when: ansible_system is undefined | default(true)

- name: include OS-specific var file
  include_vars: "{{ ansible_os_family }}.yml"

- name: include tasks for auto-patch setup
  include_tasks: patch-{{ state }}-{{ ansible_system }}.yml
