---

- name: create /etc/systemd/system/verify-reboot.service from template
  template:
    src: verify-reboot.service.j2
    dest: /etc/systemd/system/verify-reboot.service
    owner: root
    group: root
    mode: 0644
  vars:
    init_script: "{{ script_dir }}/verify-reboot.sh"
  notify: reload systemd for auto-patch
  when:
    - ansible_virtualization_type|default(None) != 'docker'
    - ansible_service_mgr == "systemd"

- name: Ensure handlers are notified now so service can be enabled
  meta: flush_handlers

- name: Ensure verify-reboot service is enabled on boot
  systemd:
    name: verify-reboot
    enabled: yes
  when:
    - ansible_virtualization_type|default(None) != 'docker'
    - ansible_service_mgr == "systemd"
